root: ./docs/

​structure:
    readme: README.md
    summary: SUMMARY.md​

redirects:
    javascript-and-and-react: ./resources/README.md
    javascript-and-and-react/: ./resources/README.md
    javascript-and-react: ./resources/README.md
    javascript-and-react/: ./resources/README.md
    deployment/deploy-on-now: ./deployment/deploy-using-now-vercel.md
    deployment/deploy-on-now/: ./deployment/deploy-using-now-vercel.md
    installation-and-deploy/deploy-on-now: ./deployment/deploy-using-now-vercel.md
    installation-and-deploy/deploy-on-now/: ./deployment/deploy-using-now-vercel.md
    installation-and-deploy: ./deployment/README.md
    installation-and-deploy/: ./deployment/README.md
    key-differences-with-gatsbyjs: ./about/README.md
    key-differences-with-gatsbyjs/: ./about/README.md
    installation-and-deploy/possible-architectures: ./architecture/architecture.md
    installation-and-deploy/possible-architectures/: ./architecture/architecture.md
    architecture: ./architecture/architecture.md
    architecture/: ./architecture/architecture.md