root: ./docs/

​structure:  
    readme: README.md  
    summary: SUMMARY.md​
    
redirects:  
    javascript-and-and-react: ./resources/README.md
    javascript-and-and-react/: ./resources/README.md
    javascript-and-react: ./resources/README.md
    javascript-and-react/: ./resources/README.md
    deploy-on-now: : ./deployment/deploy-using-now-vercel.md
    deploy-on-now/: : ./deployment/deploy-using-now-vercel.md