name: Proofread

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  proofread:
    name: Proofread
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Alex 
        uses: theashraf/alex-action@master